### ISSUE TITLE
Counts too low

### ISSUE THREAD

**Issue by nemobis** [edsu/wikipulse#3]
For the last few weeks, I've always seen wikipulse giving wrong counts on http://wikipulse.herokuapp.com/ . For instance now it says 6 edits per minute  when I'm watching a bot on wikidata which alone makes a few dozens edits per minute.

**Comment by nemobis** [comment]
Fixed by https://github.com/edsu/wikichanges/commit/50989ad94db2495f4b0393a5b565b55429145340

**Comment by edsu** [comment]
Thanks for raising this, and I'm sorry I missed it till now.
