### ISSUE TITLE
add color coded ranges to the gauges

### ISSUE THREAD

**Issue by waldyrious** [edsu/wikipulse#5]
It would be easier to compare different Wikipedias (and more visually interesting) if the gauges had ranges painted in colors (using the `greenFrom`, `yellowFrom` and `redFrom` [configuration options](https://google-developers.appspot.com/chart/interactive/docs/gallery/gauge#Configuration_Options) of the gauge chart).

I'd suggest a scale like this:
- from 0 to 60 edits per minute (below 1 edit per second): green
- from 60 e.p.m. to 300 e.p.m. (between 1 and 5 edits per second): yellow
- from 300 epm to 600 epm (between 5 and 10 edits per second): red

The implementation is simple:

``` js
var options = {
    greenFrom: 0, greenTo: 60,
    yellowFrom: 60, yellowTo: 300,
    redFrom: 300, redTo: 600,
    max: 600
}
```

This means that the max would be 600, not 500 as it currently is. Alternatively, I'd suggest maxing out at 300, since that range covers most typical values, and allows better resolution in the low-activity projects (besides, the gauge is able to properly handle abnormally high values):

``` js
var options = {
    greenFrom: 0, greenTo: 60,     // 0 to 1 edit per second
    yellowFrom: 60, yellowTo: 180, // 1 to 3 edits per second
    redFrom: 180, redTo: 300,      // 3 to 5 edits per second
    max: 300
}
```

Of course, the large cumulative gauge would have to use a different scale, say 1200 max instead of 1500; so the ranges would be doubled if we use 600 as a single-project max, or quadrupled if we use 300.

If this is a change that would be welcome, I can submit a PR.

**Comment by edsu** [comment]
Sounds great, a PR would be most welcome!
